export const SET_LOGIN_USER_INFO = 'SET_LOGIN_USER_INFO';

export const SET_SYSTEM_SETTING = 'SET_SYSTEM_SETTING';

export const SET_SYSTEM_VERSION = 'SET_SYSTEM_VERSION';

export const SET_ALL_PRIVILEGES = 'SET_ALL_PRIVILEGES';

export const SET_MEMBER_ACCOUNT_RULES = 'SET_MEMBER_ACCOUNT_RULES';

export const SET_AREALIST = 'SET_AREALIST';

export const SET_FROMHOMEPAGE = 'SET_FROMHOMEPAGE';

export const SET_CURRENT_COLLEGE = 'SET_CURRENT_COLLEGE';
