export const consoleIcons = [
    {name:'点赞',icon:'console-icondianzan'},
    {name:'点赞',icon:'console-icondianzan_kuai'},
    {name:'爱心',icon:'console-iconaixin'},
    {name:'爱心',icon:'console-iconaixin_shixin'},
    {name:'发布',icon:'console-iconicon_fabu'},
    {name:'发布',icon:'console-iconfabusekuai'},

    {name:'列表',icon:'console-iconliebiao'},
    {name:'刷新',icon:'console-iconyunduanshuaxin'},
    {name:'存储',icon:'console-iconchucun'},
    {name:'数据挖掘',icon:'console-iconshujuwajue'},
    {name:'魔术棒',icon:'console-iconmoshubang'},
    {name:'待办事项',icon:'console-icondaibanshixiang'},
    {name:'安全',icon:'console-iconanquan'},
    {name:'查询',icon:'console-iconchaxun'},

    {name:'地标',icon:'console-iconditu-dibiao'},
    {name:'旗帜',icon:'console-iconditu-qi'},
    {name:'消息',icon:'console-iconxiaoxi'},
    {name:'广播',icon:'console-iconguangbo'},
    {name:'告警',icon:'console-icongaojing1'},
    {name:'告警',icon:'console-icongaojing'},
    {name:'优惠',icon:'console-iconyouhui'},
    {name:'消息通知',icon:'console-iconxiaoxitongzhi'},
    {name:'客服',icon:'console-iconkefu'},
    {name:'问题解答',icon:'console-iconwentijieda'},
    {name:'帮助文档',icon:'console-iconicon_bangzhuwendang'},
    {name:'使用文档',icon:'console-iconicon_shiyongwendang'},
    {name:'使用文档',icon:'console-iconshiyongwendang'},

    {name:'工单',icon:'console-icongongdan'},
    {name:'工单确认',icon:'console-icongongdanqueren'},
    {name:'执行反馈',icon:'console-iconzhihangfankui'},
    {name:'软件包开发',icon:'console-iconruanjiankaifabao'},
    {name:'app开发',icon:'console-iconAPPkaifa'},

    {name:'快速编排',icon:'console-iconkuaisubianpai'},
    {name:'设备状态',icon:'console-iconshebeizhuangtai'},
    {name:'设备管理',icon:'console-iconshebeiguanli'},
    {name:'上传',icon:'console-iconyunduanshangchuan'},

    {name:'PNG',icon:'console-iconPNG'},
    {name:'JPG',icon:'console-iconJPG'},
    {name:'GIF',icon:'console-iconGIF'},
    {name:'BMP',icon:'console-iconBMP'},
    {name:'DOC',icon:'console-iconDOC'},
    {name:'文件夹',icon:'console-iconwenjianjia'},

    {name:'回形针',icon:'console-iconhuixingzhen'},
    {name:'显号',icon:'console-iconxianhao'},
    {name:'密文',icon:'console-iconmiwen'},
    {name:'中文',icon:'console-iconzhongwen'},
    {name:'英文',icon:'console-iconyingwen'},

    {name:'打开',icon:'console-icondakai'},
    {name:'分组管理',icon:'console-iconfenzuguanli'},
    {name:'组织群组',icon:'console-iconzuzhiqunzu'},
    {name:'组织下辖',icon:'console-iconzuzhixiaxia'},
    {name:'运营中心',icon:'console-iconyunyingzhongxin'},
    {name:'运营管理',icon:'console-iconyunyingguanli'},
    {name:'技术服务',icon:'console-iconjishufuwu1'},
    {name:'技术服务',icon:'console-iconjishufuwu'},
    {name:'功能定义',icon:'console-icongongnengdingyi1'},

    {name:'数据看板',icon:'console-iconshujukanban'},
    {name:'图片',icon:'console-iconxingzhuang-tupian'},
    {name:'箭头',icon:'console-iconxingzhuang-jianxing'},
    {name:'柱状图',icon:'console-icontubiao-zhuzhuangtu'},
    {name:'折线图',icon:'console-icontubiao-zhexiantu'},
    {name:'卡片',icon:'console-icontubiao-qiapian'},
    {name:'饼图',icon:'console-icontubiao-bingtu'},

    {name:'仪表盘',icon:'console-icongongyezujian-yibiaopan'},
    {name:'仪表盘',icon:'console-iconyibiaopan'},
    {name:'应用管理',icon:'console-iconicon_yingyongguanli'},
    {name:'应用管理',icon:'console-iconyingyongguanli'},

    {name:'设置',icon:'console-iconicon_shezhi'},
    {name:'网页',icon:'console-iconicon_wangye'},
    {name:'账号',icon:'console-iconicon_zhanghao'},

    {name:'疑问',icon:'console-iconicon_yiwenkongxin'},
    {name:'入口',icon:'console-iconicon_rukou'},
    {name:'任务进程',icon:'console-iconicon_renwujincheng'},
    {name:'自定义',icon:'console-iconzidingyi'},
    {name:'基站管理',icon:'console-iconjizhanguanli'},
    {name:'园区维护',icon:'console-iconyuanquyunwei'},
    {name:'账号权限',icon:'console-iconzhanghaoquanxianguanli'},

    {name:'提案审批',icon:'console-icontianshenpi'},
    {name:'已授权',icon:'console-iconyishouquan'},
    {name:'权限审批',icon:'console-iconquanxianshenpi'},
    {name:'人机交互',icon:'console-iconrenjijiaohu'},
    {name:'配网引导',icon:'console-iconpeiwangyindao'},
    {name:'警告',icon:'console-iconjinggao'},
    {name:'节点管理',icon:'console-iconjiedianguanli'},
    {name:'测试申请',icon:'console-iconceshishenqing'},
    {name:'密钥',icon:'console-iconhezuohuobanmiyueguanli'},
    {name:'基础管理',icon:'console-iconjichuguanli'},
    {name:'功能定义',icon:'console-icongongnengdingyi'},
    {name:'官方版本',icon:'console-iconguanfangbanben'},
    {name:'关联设备',icon:'console-iconguanlianshebei'},
    {name:'场景管理',icon:'console-iconchangjingguanli'},
    {name:'调试',icon:'console-icontiaoshi'},
];
